tap "homebrew/bundle"

brew "git"
brew "gh"
brew "jq"
brew "ripgrep"
brew "fd"
brew "eza"
brew "bat"
brew "procs"
brew "fzf"
brew "zoxide"
brew "mise"
brew "uv"
brew "direnv"
brew "tmux"
brew "mas"
brew "nmap"
brew "arp-scan"
brew "ccrypt"
brew "pwgen"
brew "speedtest-cli"
brew "thefuck"

cask "cursor"
cask "google-chrome"
cask "google-japanese-ime"
cask "iterm2"
cask "slack"
cask "firefox"
cask "powershell"
cask "docker"
cask "dbeaver-community"
cask "font-hackgen"

# Optional App Store apps
# mas "Xcode", id: 497799835
# mas "Pages", id: 409201541
