pkglist=(
abusaidm.html-snippets
amazonwebservices.aws-toolkit-vscode
CoenraadS.bracket-pair-colorizer
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
donjayamanne.githistory
eamodio.gitlens
EditorConfig.EditorConfig
eriklynd.json-tools
eserozvataf.one-dark-pro-monokai-darker
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
GitHub.vscode-pull-request-github
GrapeCity.gc-excelviewer
jsjlewis96.one-dark-pro-italic-vivid
marp-team.marp-vscode
mauve.terraform
mechatroner.rainbow-csv
ms-azuretools.vscode-azureterraform
ms-azuretools.vscode-docker
ms-mssql.mssql
ms-python.python
ms-vscode.azure-account
ms-vscode.azurecli
ms-vscode.powershell
ms-vsliveshare.vsliveshare
octref.vetur
oderwat.indent-rainbow
phplasma.csv-to-table
PKief.material-icon-theme
shardulm94.trailing-spaces
shd101wyy.markdown-preview-enhanced
shinnn.stylelint
thomas-baumgaertner.vcl
william-voyek.vscode-nginx
zhuangtongfa.material-theme
Zignd.html-css-class-completion
)

for i in ${pkglist[@]}; do
  code --install-extension $i
done